version: '3.1'

services:
  web:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./data:/data
    links:
      - php
  php:
    build: ./php/.
    volumes:
      - ./src:/var/www/html
      - ./data:/data
